# Generated by Django 5.0.7 on 2024-07-14 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'categoria_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateField()),
                ('porc_dcto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despacho', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('valor_envio', models.IntegerField()),
                ('fecha_entrega', models.DateField()),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoDespacho',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'estado_despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_compra', models.OneToOneField(db_column='id_compra', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataManager.compra')),
                ('cant_producto', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dataManager.usuario')),
                ('fecha_inicio_susc', models.DateField()),
                ('fecha_fin_susc', models.DateField()),
            ],
            options={
                'db_table': 'suscriptor',
                'managed': False,
            },
        ),
    ]
