-- CREAR USUARIO --
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER LOS_VERDINOS_BD IDENTIFIED BY "verdinos"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";
ALTER USER LOS_VERDINOS_BD QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO LOS_VERDINOS_BD;
GRANT CONNECT TO LOS_VERDINOS_BD;
GRANT "RESOURCE" TO LOS_VERDINOS_BD;
ALTER USER LOS_VERDINOS_BD DEFAULT ROLE "RESOURCE";
