-- ELIMINAR TABLAS --
DROP TABLE USUARIO CASCADE CONSTRAINTS;
DROP TABLE SUSCRIPTOR CASCADE CONSTRAINTS;
DROP TABLE CARRITO CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;


-- TABLA | USUARIO --
CREATE TABLE USUARIO (
    id_usuario NUMBER(5) GENERATED ALWAYS AS IDENTITY
    START WITH 1
    INCREMENT BY 1,
    
    nombre VARCHAR2(50) NOT NULL,
    apellido VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    clave VARCHAR2(50) NOT NULL,
    
    -- PRIMARY KEY | ID_USUARIO --
    CONSTRAINT PK_USUARIO PRIMARY KEY (id_usuario)
);

-- TABLA | SUSCRIPTOR --
CREATE TABLE SUSCRIPTOR (
    id_usuario NUMBER(5) PRIMARY KEY,
    fecha_inicio_susc DATE,
    fecha_fin_susc DATE,
   
    -- FOREIGN KEY | ID_USUARIO --
    CONSTRAINT FK_SUSCRIPTOR_USUARIO FOREIGN KEY (id_usuario)
    REFERENCES USUARIO (id_usuario)
);

-- TABLA | CARRITO --
CREATE TABLE CARRITO (
    id_carrito NUMBER(5) GENERATED ALWAYS AS IDENTITY
    START WITH 1
    INCREMENT BY 1,
    id_usuario NUMBER(5),
    
    -- PRIMARY KEY | ID_CARRITO --
    CONSTRAINT PK_CARRITO PRIMARY KEY (id_carrito),
    
    -- FOREIGN KEY | ID_USUARIO --
    CONSTRAINT FK_CARRITO_USUARIO FOREIGN KEY (id_usuario)
    REFERENCES USUARIO (id_usuario)
);

-- TABLA | CATEGORIA_PRODUCTO --
CREATE TABLE CATEGORIA_PRODUCTO (
    id_categ_prod NUMBER(5) GENERATED ALWAYS AS IDENTITY
    START WITH 1
    INCREMENT BY 1,
    nombre_categ VARCHAR2(40),
    
    -- PRIMARY KEY | ID_CATEG_PROD --
    CONSTRAINT PK_CATEGORIA_PRODUCTO PRIMARY KEY (id_categ_prod)
);

-- TABLA | PRODUCTO --
CREATE TABLE PRODUCTO (
    id_producto NUMBER(5) GENERATED ALWAYS AS IDENTITY
    START WITH 1
    INCREMENT BY 1,
    nombre VARCHAR2(40),
    stock NUMBER(3),
    precio NUMBER(6),
    descripcion VARCHAR2(150),
    id_categ_prod NUMBER,
    
    -- PRIMARY KEY | ID_PRODUCTO --
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (id_producto),
    
    -- FOREIGN KEY | ID_CATEG_PROD --
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (id_categ_prod)
    REFERENCES CATEGORIA_PRODUCTO(id_categ_prod)
);

-- TABLA | DETALLE_CARRITO --
CREATE TABLE DETALLE_CARRITO (
    id_carrito NUMBER(5) PRIMARY KEY,
    id_producto NUMBER(5),
    cant_producto NUMBER(3),
    total NUMBER(5),
    
    -- FOREIGN KEY | ID_CARRITO --
    CONSTRAINT FK_DET_PRODUCTO FOREIGN KEY (id_producto)
    REFERENCES PRODUCTO (id_producto),
    
    -- FOREIGN KEY | ID_CARRITO --
    CONSTRAINT FK_DET_CARRITO FOREIGN KEY (id_carrito)
    REFERENCES CARRITO (id_carrito)
);

-- TABLA | PEDIDO --
CREATE TABLE PEDIDO (
    nro_pedido NUMBER GENERATED ALWAYS AS IDENTITY
    START WITH 1
    INCREMENT BY 1,
    
);